import React from 'react'
import Head from 'next/head'
import { DataContextProvider } from '../context/dataContext'

const Layout = ({ children }) => {
  return (
    <>
      <Head>
        <title>Brewery Db</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <header></header>
      <DataContextProvider>
        <main>{children}</main>
      </DataContextProvider>
      <footer className='footer'>ITT MAJD VALAMI LESZ</footer>
    </>
  )
}

export default Layout
