import React from 'react'
import Head from 'next/head'
import { DataContextProvider } from '../context/dataContext'
import {Navbar, Container} from 'react-bootstrap'
import 'bootstrap/dist/css/bootstrap.min.css'

const Layout = ({ children }) => {
  return (
    <>
      <Head>
        <title>Brewery Db</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <header>
        <>
          <Navbar variant='dark' fixed="top" >
            <Container>
              <Navbar.Brand href='/'>
                <img
                  alt=''
                  src='./images/logo.png'
                  width='50'
                  height='50'
                  className='d-inline-block align-top'
                />{' '}
                <span className='brand-name'>Brewery Db</span> 
              </Navbar.Brand>
            </Container>
          </Navbar>
        </>
      </header>
      <DataContextProvider>
        <main>{children}</main>
      </DataContextProvider>
    </>
  )
}

export default Layout
